// AUTO-GENERATED BY OPACA — do not edit manually
// Instead edit your collections and run `opaca dev` or `bun run opaca:build`
import * as config from "@opaca-config";
import { buildDrizzleTable } from "@opaca/builder/build";
export const posts = buildDrizzleTable(config.serverConfig.collections["posts"], "d1");
export const products = buildDrizzleTable(config.serverConfig.collections["products"], "d1");
export const users = buildDrizzleTable(config.serverConfig.collections["users"], "d1");
export const properties = buildDrizzleTable(config.serverConfig.collections["properties"], "d1");
export const logs = buildDrizzleTable(config.serverConfig.collections["logs"], "d1");