// AUTO-GENERATED BY OPACA — do not edit manually
// Instead edit your collections and run `opaca dev`
import { client } from "@opaca-config";
import { buildDrizzleTable } from "@opaca/db/builder/build";
export const posts = buildDrizzleTable(client.collections["posts"], "d1");
export const products = buildDrizzleTable(client.collections["products"], "d1");
export const users = buildDrizzleTable(client.collections["users"], "d1");
export const properties = buildDrizzleTable(client.collections["properties"], "d1");
export const logs = buildDrizzleTable(client.collections["logs"], "d1");