// AUTO-GENERATED BY OPACA — do not edit manually
// Instead edit your collections and run `opaca dev` or `bun run opaca:build`
import config from "@opaca-config";
import { buildDrizzleTable } from "@/opaca/db/builder/build";
export const posts = buildDrizzleTable(config.collections["posts"], "d1");
export const products = buildDrizzleTable(config.collections["products"], "d1");
export const users = buildDrizzleTable(config.collections["users"], "d1");
export const properties = buildDrizzleTable(config.collections["properties"], "d1");
export const logs = buildDrizzleTable(config.collections["logs"], "d1");